[tool.poetry]
name = "py-test"
version = "0.0.1"
description = "Test"
authors = ["Siarhei <siarhei.baltsevich.jazzteam@gmail.com>"]
license = "Mit"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
